# Generated by Django 5.2.7 on 2025-10-03 02:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corredor', models.CharField(help_text='Corredor responsable.', max_length=120)),
                ('instrumento', models.CharField(help_text='Identificador del instrumento.', max_length=120)),
                ('anio_tributario', models.PositiveIntegerField(help_text='Anio tributario (ej 2025).')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('f8', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True)),
                ('f9', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True)),
                ('f10', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True)),
                ('f11', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True)),
                ('f12', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True)),
                ('f13', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True)),
                ('f14', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True)),
                ('f15', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True)),
                ('f16', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True)),
                ('f17', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True)),
                ('f18', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True)),
                ('f19', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VIGENTE', 'Vigente'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-actualizado_en'],
                'indexes': [models.Index(fields=['corredor'], name='calificacio_corredo_c9c54c_idx'), models.Index(fields=['anio_tributario'], name='calificacio_anio_tr_414c9e_idx')],
            },
        ),
    ]
