# Generated by Django 5.2.7 on 2025-10-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='anio_tributario',
            field=models.PositiveIntegerField(help_text='Año tributario (ej 2025)', verbose_name='Año tributario'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='corredor',
            field=models.CharField(help_text='Corredor responsable', max_length=120),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='instrumento',
            field=models.CharField(help_text='Identificador del instrumento', max_length=120),
        ),
    ]
