# Generated by Django 4.2 on 2025-10-31 16:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_alter_calificacion_anio_tributario_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calificacion',
            name='calificacio_corredo_c9c54c_idx',
        ),
        migrations.RemoveIndex(
            model_name='calificacion',
            name='calificacio_anio_tr_414c9e_idx',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='anio_tributario',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='corredor',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='f10',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='f11',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='f12',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='f13',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='f14',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='f15',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='f16',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='f17',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='f18',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='f19',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='f8',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='f9',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='monto',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='ejercicio',
            field=models.IntegerField(default=2023, help_text='Ejercicio', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2070)], verbose_name='Ejercicio'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor1',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor10',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor11',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor12',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor13',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor14',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor15',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor16',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor17',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor18',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor19',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor2',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor20',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor21',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor22',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor23',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor24',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor25',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor26',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor3',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor4',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor5',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor6',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor7',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor8',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor9',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='fecha',
            field=models.DateField(default='2023-01-01', help_text='Fecha (DD-MM-AAAA)'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='isfut_casilla',
            field=models.CharField(blank=True, default='', help_text='ISFUT Casilla', max_length=120),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='mercado',
            field=models.CharField(default='', help_text='Mercado', max_length=120),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='numero_dividendo',
            field=models.IntegerField(default=0, help_text='Número de dividendo', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de dividendo'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='secuencia',
            field=models.IntegerField(default=0, help_text='Secuencia', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Secuencia'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='tipo_sociedad',
            field=models.CharField(choices=[('A', 'Abierta'), ('C', 'Cerrada')], default='A', help_text='Tipo sociedad A/C', max_length=1),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='valor_historico',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN PROCESO', 'En Proceso'), ('VIGENTE', 'Vigente'), ('ANULADA', 'Anulada'), ('INVALIDO', 'Inválido')], default='BORRADOR', max_length=12),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='instrumento',
            field=models.CharField(default='', help_text='Instrumento', max_length=120),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['ejercicio'], name='calificacio_ejercic_2c7c20_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['mercado'], name='calificacio_mercado_f5f740_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['instrumento'], name='calificacio_instrum_e667ba_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['estado'], name='calificacio_estado_78bf57_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['ejercicio', 'mercado'], name='calificacio_ejercic_0a770a_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['instrumento', 'estado'], name='calificacio_instrum_f9ded7_idx'),
        ),
    ]
