# Generated by Django 4.2 on 2025-10-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_remove_calificacion_calificacio_corredo_c9c54c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor_actualizacion',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Factor de Actualización'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='isfut_casilla',
            field=models.BooleanField(default=False, verbose_name='ISFUT'),
        ),
    ]
