# Generated by Django 4.2 on 2025-10-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_calificacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='origen',
            field=models.CharField(choices=[('CORREDORA', 'Corredora'), ('SISTEMA', 'Sistema')], default='CORREDORA', help_text='Origen', max_length=20),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='tipo_mercado',
            field=models.CharField(choices=[('ACCIONES', 'Acciones'), ('CFI', 'CFI'), ('FONDOS_MUTUOS', 'Fondos Mutuos')], default='ACCIONES', help_text='Tipo de Mercado', max_length=20),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['tipo_mercado'], name='calificacio_tipo_me_087baf_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['origen'], name='calificacio_origen_fd7ba1_idx'),
        ),
    ]
