# Generated by Django 4.2 on 2025-10-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0005_calificacion_origen_calificacion_tipo_mercado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='tipo_mercado',
            field=models.CharField(choices=[('ACCIONES', 'Acciones'), ('CFI', 'CFI'), ('FONDOS_MUTUOS', 'Fondos Mutuos'), ('ISIFT', 'ISIFT')], default='ACCIONES', help_text='Tipo de Mercado', max_length=20),
        ),
    ]
