# Generated by Django 4.2 on 2025-11-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0006_alter_calificacion_tipo_mercado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='ejercicio',
            field=models.DateField(default='2025-01-01', help_text='Fecha pago', verbose_name='Fecha pago'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha',
            field=models.DateField(default='2025-01-01', help_text='Fecha (DD-MM-AAAA)'),
        ),
    ]
